trigger: none

pr: none

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true
- task: OneLocBuild@2
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    locProj: 'src/LocProject.json'
    outDir: '$(Build.ArtifactStagingDirectory)'
    isCreatePrSelected: true
    repoType: 'gitHub'
    prSourceBranchPrefix: 'locfiles'
    gitHubPrMergeMethod: 'squash'
    packageSourceAuth: 'patAuth'
    patVariable: '$(OneLocBuildPat)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'