trigger: none
pr:
  - master
strategy:
  matrix:
    mac-x64:
      platform: 'mac-x64'
      imageName: 'macOS-latest'
      archiveType: 'tar'
    mac-arm64:
      platform: 'mac-arm64'
      imageName: 'macOS-latest'
    windows:
      platform: 'windows'
      imageName: 'windows-latest'
pool:
  vmImage: $(imageName)
steps:
- template: templates/build.yml