trigger: none
pr:
  - master
strategy:
  matrix:
    linux:
      platform: 'linux'
      imageName: 'ubuntu-latest'
      archiveType: 'tar'
    mac-x64:
      platform: 'mac-x64'
      imageName: 'macOS-latest'
      archiveType: 'tar'
    mac-arm64:
      platform: 'mac-arm64'
      imageName: 'macOS-latest'
    ubuntu:
      platform: 'ubuntu'
      imageName: 'ubuntu-latest'
      archiveType: 'tar'
    windows:
      platform: 'windows'
      imageName: 'windows-latest'
pool:
  vmImage: $(imageName)
steps:
- template: templates/build.yml
- template: templates/code-sign.yml